services:
  app:
    build: .
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=axelor
      - PGPASSWORD=axelor
      - PGDATABASE=axelor
      - DEV_MODE=true
      - JAVA_XMX=4096m
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=axelor
      - POSTGRES_PASSWORD=axelor
      - POSTGRES_DB=axelor