services:
  app:
    image: axelor/aos-ce:latest
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=axelor
      - PGPASSWORD=axelor
      - PGDATABASE=axelor
      - DEV_MODE=true
      - JAVA_XMX=4096m
    ports:
      - "8080:8080"
    volumes:
      - app_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1800s
  goovee:
    build:
      context: .
    depends_on:
      - postgres
      - app
    environment:
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=axelor
      - PGPASSWORD=axelor
      - PGDATABASE=axelor
      # Host environment variables
      - DATA_STORAGE
      - MULTI_TENANCY
      - INCLUDE_LANGUAGE
      - NEXT_PUBLIC_HOST
      - NEXT_PUBLIC_AOS_URL
      - NEXTAUTH_URL
      - NEXTAUTH_SECRET
      - BASIC_AUTH_USERNAME
      - BASIC_AUTH_PASSWORD
      - TENANT_MANAGER_BASIC_USERNAME
      - TENANT_MANAGER_BASIC_PASSWORD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - PAYPAL_CLIENT_ID
      - PAYPAL_CLIENT_SECRET
      - NEXT_PUBLIC_PAYPAL_CLIENT_ID
      - STRIPE_CLIENT_ID
      - STRIPE_CLIENT_SECRET
      - NEXT_PUBLIC_STRIPE_CLIENT_ID
      - PBX_RANG
      - PBX_IDENTIFIANT
      - PBX_SITE
      - PBX_PAYBOX
      - PBX_BACKUP1
      - PBX_BACKUP2
      - PBX_SECRET
      - NEXT_PUBLIC_MATTERMOST_HOST
      - NEXT_PUBLIC_MATTERMOST_WEBSOCKET_URL
      - MAIL_HOST
      - MAIL_PORT
      - MAIL_SECURE
      - MAIL_USER
      - MAIL_PASSWORD
      - MAIL_EMAIL
      - NEXT_PUBLIC_LINKEDIN_URL
      - NEXT_PUBLIC_TWITTER_URL
      - NEXT_PUBLIC_INSTAGRAM_URL
      - NEXT_PUBLIC_WHATSAPP_URL
    volumes:
      - app_data:/data
    ports:
      - "3000:3000"
  postgres:
    image: "postgres:16"
    environment:
      - POSTGRES_USER=axelor
      - POSTGRES_PASSWORD=axelor
      - POSTGRES_DB=axelor
volumes:
  app_data: