name: AOS CE

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker buildx build --build-arg AOP_VERSION=${{ env.AOP_VERSION || 'latest' }} --build-arg AOS_VERSION=${{ env.AOS_VERSION || 'master' }} --tag axelor/aos-ce:${{ env.DOCKER_TAG || 'latest' }} aos-ce
    
    - name: Push to Docker Hub
      run: docker push axelor/aos-ce:${{ env.DOCKER_TAG || 'latest' }}
